#!/bin/bash

HALLO DIT IS EEN TOEVOEGING
EENS EVEN KIJKEN OF DIT WERKT 

# alle arguments op een rijtje;
# rm [bestandsnaam]  ; verwijdert een bestand door het te zippen en naar trash te verhuizen
# rm -u [bestandsnaam]   ; maakt het verwijderen ongedaan
# rm -p [wachtwoord] [bestandsnaam]  ; verwijdert een bestand door het naar trash te verhuizen met een wachtwoord
# rm -u [bestandsnaam] ;  als het bestand met een wachtwoord beveiligd is, dan wordt er gevraagd om het wachtwoord voordat je het terug kan halen
# rm -r [foldernaam] ; verwijdert een hele folder met alles erin
# rm -u [foldernaam] ; maakt het verwijderen van een folder ongedaan
# rm -r -p [wachtwoord] [foldernaam] ; verwijdert een folder met alles erin en beveiligt het met een wachtwoord
# rm -u [foldernaam] ; maakt het verwijderen van een folder ongedaan en als er een wachtwoord bij zat dan vraagt hij om het wachtwoord



#ik maak een Main functie zodat we die aan het eind als alias kunnen gebruiken.
#alles gebeurt in Main


Main(){



MakeTrashFolder(){
    #deze functie maakt de trash folder in de home directory, indien die nog niet bestaat.
    #als de trash folder wel al bestaat, gaat er ook niks mis of iets.
    mkdir -p  ~/trash
}
MakeTrashFolder

}


alias rm=Main

